language: ruby

rvm:
  - 2.3.3

script:
  - bundle exec rake db:create:all
  - bundle exec rake dv:migrate RAILS_ENV=test
  - ruby -Itest test/models/advogado_test.rb
  - ruby -Itest test/models/processo_test.rb
  - ruby -Itest test/models/user_test.rb
  - ruby -S bundle exec cucumber --profile default

services:
  - postgresql